version: '2'
services: 
  api:
    build: ./deploy-api
    ports:
    - "8091:8091"
    links:
    - db
  db:
    image: mongo
    expose:
    - "27017"
  web:
    build: ./deploy-web
    ports: 
    - "8090:8090"
    links:
    - db
