version: '2'
services: 
  api:
    build: ./deploy-api
    ports:
    - "8091:8091"
    links:
    - db
  db:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=DEEPLOY
    expose:
    - "3306"
  web:
    build: ./deploy-web
    ports: 
    - "8090:8090"
    links:
    - db
