DROP DATABASE IF EXISTS DEEPLOY;
CREATE DATABASE DEEPLOY;

USE DEEPLOY;

CREATE TABLE BUILD_FLOW (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(256),
    PRIMARY KEY (ID)
);

CREATE TABLE BUILD_FLOW_STEP (
    ID INT AUTO_INCREMENT,
    BUILD_FLOW_ID INT,
    EXECUTOR_NAME VARCHAR(256),
    FOREIGN KEY (BUILD_FLOW_ID) REFERENCES BUILD_FLOW (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE BUILD_FLOW_STEP_ARGUMENT (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(256),
    VALUE VARCHAR(256),
    BUILD_FLOW_STEP_ID INT,
    FOREIGN KEY (BUILD_FLOW_STEP_ID) REFERENCES BUILD_FLOW_STEP (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE BUILD_FLOW_EXECUTION_HISTORY (
    ID INT AUTO_INCREMENT,
    START_TIME DATETIME,
    BUILD_FLOW_ID INT,
    FOREIGN KEY (BUILD_FLOW_ID) REFERENCES BUILD_FLOW (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE BUILD_FLOW_STEP_EXECUTION_HISTORY (
    ID INT AUTO_INCREMENT,
    START_TIME DATETIME,
    BUILD_FLOW_EXECUTION_HISTORY_ID INT,
    BUILD_FLOW_STEP_ID INT,
    FOREIGN KEY (BUILD_FLOW_EXECUTION_HISTORY_ID) REFERENCES BUILD_FLOW_EXECUTION_HISTORY (ID),
    FOREIGN KEY (BUILD_FLOW_STEP_ID) REFERENCES BUILD_FLOW_STEP (ID),
    PRIMARY KEY (ID)
);

