CREATE DATABASE DEEPLOY;

USE DEEPLOY;

CREATE TABLE BUILD_FLOW (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(256),
    PRIMARY KEY (ID)
);

CREATE TABLE BUILD_FLOW_STEP (
    ID INT AUTO_INCREMENT,
    BUILD_FLOW_ID INT,
    EXECUTOR_ID INT,
    FOREIGN KEY (BUILD_FLOW_ID) REFERENCES BUILD_FLOW (ID),
    FOREIGN KEY (EXECUTOR_ID) REFERENCES EXECUTOR (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE BUILD_FLOW_STEP_ARGUMENT (
    ID INT AUTO_INCREMENT,
    VALUE VARCHAR(256),
    EXECUTOR_ARGUMENT_ID INT,
    BUILD_FLOW_STEP_ID INT,
    FOREIGN KEY (BUILD_FLOW_STEP_ID) REFERENCES BUILD_FLOW_STEP (ID),
    FOREIGN KEY (EXECUTOR_ARGUMENT_ID) REFERENCES EXECUTOR_ARGUMENT (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE EXECUTOR (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(256),
    TYPE VARCHAR(64),
    PRIMARY KEY (ID)
);

CREATE TABLE EXECUTOR_ARGUMENT (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(256),
    MANDATORY TINYINT(1),
    "DEFAULT" VARCHAR(4096) DEFAULT NULL,
    EXECUTOR_ID INT,
    FOREIGN KEY (EXECUTOR_ID) REFERENCES EXECUTOR (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE BUILD_FLOW_EXECUTION_HISTORY (
    ID INT AUTO_INCREMENT,
    START_TIME DATETIME,
    BUILD_FLOW_ID INT,
    FOREIGN KEY (BUILD_FLOW_ID) REFERENCES BUILD_FLOW (ID),
    PRIMARY KEY (ID)
);

CREATE TABLE BUILD_FLOW_STEP_EXECUTION_HISTORY (
    ID INT AUTO_INCREMENT,
    START_TIME DATETIME,
    BUILD_FLOW_EXECUTION_HISTORY_ID INT,
    BUILD_FLOW_STEP_ID INT,
    FOREIGN KEY (BUILD_FLOW_EXECUTION_HISTORY_ID) REFERENCES BUILD_FLOW_EXECUTION_HISTORY (ID),
    FOREIGN KEY (BUILD_FLOW_STEP_ID) REFERENCES BUILD_FLOW_STEP (ID),
    PRIMARY KEY (ID)
);
