CREATE DATABASE DEPLOYER;

USE DEPLOYER;

CREATE TABLE CREDENTIALS (
    ID INT AUTO_INCREMENT,
    USERNAME VARCHAR(64),
    PASSWORD VARCHAR(512),
    KEY_LOCATION VARCHAR(512),
    TYPE VARCHAR(64),
    PRIMARY KEY (ID)
);

CREATE TABLE SERVER (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(256),
    HOST VARCHAR(256),
    CREDENTIALS_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (CREDENTIALS_ID) REFERENCES CREDENTIALS(ID)
);

CREATE TABLE SERVER_ARTIFACT_JOIN (
    ID INT AUTO_INCREMENT,
    SERVER_ID INT,
    ARTIFACT_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (SERVER_ID) REFERENCES SERVER(ID),
    FOREIGN KEY (ARTIFACT_ID) REFERENCES ARTIFACT(ID)
);

CREATE TABLE ARTIFACT (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(256),
    PRIMARY KEY (ID)
);

CREATE TABLE ARTIFACT_VERSION (
    ID INT AUTO_INCREMENT,
    ARTIFACT_LOCATION VARCHAR(512),
    ARTIFACT_LOCATION_TYPE VARCHAR(64),
    VERSION VARCHAR(32),
    DEPLOYMENT_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (DEPLOYMENT_ID) REFERENCES DEPLOYMENT(ID)
);
